apiVersion: v1
kind: ConfigMap
metadata:
  name: gateway-service
data:
  application-kubernetes.yml: |-
    server:
      shutdown: graceful
    spring:
      config:
        activate:
          on-profile: kubernetes
      cloud:
        gateway:
          discovery:
            locator:
              enabled: true
              lower-case-service-id: true
          routes:
            - id: openapi
              uri: lb://gateway-service
              predicates:
                - Path=/v3/api-docs/**
              filters:
                - RewritePath=/v3/api-docs/(?<path>.*), /$\{path}/v3/api-docs
        loadbalancer:
          ribbon:
            enabled: false
        kubernetes:
          reload:
            enabled: true
            mode: polling
            period: 10000
          config:
            sources:
              - name: ${spring.application.name}
