server:
  port: 8000
spring:
  config:
    activate:
      on-profile: local
  cloud:
    kubernetes:
      enabled: false
    stream:
      kafka.binder:
        brokers: 192.168.64.3:32100
  messages:
    cache-duration: -1
  r2dbc:
    url: r2dbc:pool:mysql://192.168.64.3:30306/eventstore?useSSL=false
    username: root
    password: passw0rd
  flyway:
    schemas: eventstore
    url: jdbc:mysql://192.168.64.3:30306/?allowPublicKeyRetrieval=true&useSSL=false
    user: ${spring.r2dbc.username}
    password: ${spring.r2dbc.password}
    baseline-on-migrate: true
    placeholder-replacement: false
logging:
  level:
    org.springframework.r2dbc: DEBUG
